#!/usr/bin/env bash
# this command outputs "bad luck" after 4, 9, and 17
x=0
while (( x < 20 ))
	do
		((x++))
		case $x in
			4)
				echo "bad luck from China"
				;;
			9)
				echo "bad luck from Japan"
				;;
			17)
				echo "bad luck from Italy"
				;;
		esac
	done
